export interface ParamDefinition {
  id: string
  name: string
  type: 'flag' | 'value'
  valueType?: 'boolean' | 'number' | 'string' | 'select' | 'path'
  label: string
  description: string
  defaultValue?: any
  options?: string[]
  placeholder?: string
  category: string
  priority?: number
  dependencies?: string[]
  outputFormats?: string[]
}

export const PARAM_DEFINITIONS: ParamDefinition[] = [
  {
    id: 'toc',
    name: '--toc',
    type: 'flag',
    valueType: 'boolean',
    label: '生成目录',
    description: '在输出文档中自动生成目录',
    category: '常用参数',
    priority: 1,
  },
  {
    id: 'toc-depth',
    name: '--toc-depth',
    type: 'value',
    valueType: 'number',
    label: '目录深度',
    description: '设置目录包含的标题层级深度',
    defaultValue: 3,
    placeholder: '输入1-6的数字',
    category: '常用参数',
    priority: 2,
    dependencies: ['toc'],
  },
  {
    id: 'number-sections',
    name: '--number-sections',
    type: 'flag',
    valueType: 'boolean',
    label: '章节编号',
    description: '自动对章节进行编号',
    category: '常用参数',
    priority: 3,
  },
  {
    id: 'section-divs',
    name: '--section-divs',
    type: 'flag',
    valueType: 'boolean',
    label: '章节分隔',
    description: '用 div 标签包裹章节内容',
    category: '文档结构',
    priority: 4,
  },
  {
    id: 'standalone',
    name: '--standalone',
    type: 'flag',
    valueType: 'boolean',
    label: '独立文档',
    description: '生成完整的独立文档（包含头部和尾部）',
    category: '常用参数',
    priority: 5,
  },
  {
    id: 'page-size',
    name: '--page-size',
    type: 'value',
    valueType: 'select',
    label: '页面大小',
    description: '设置 PDF 输出的页面大小',
    defaultValue: 'a4',
    options: ['a4', 'letter', 'a5', 'legal'],
    category: '页面设置',
    priority: 7,
    outputFormats: ['pdf'],
  },
  {
    id: 'margin-top',
    name: '--margin-top',
    type: 'value',
    valueType: 'string',
    label: '上边距',
    description: '设置页面上边距',
    placeholder: '如 2cm 或 1in',
    category: '页面设置',
    priority: 8,
    outputFormats: ['pdf'],
  },
  {
    id: 'margin-bottom',
    name: '--margin-bottom',
    type: 'value',
    valueType: 'string',
    label: '下边距',
    description: '设置页面下边距',
    placeholder: '如 2cm 或 1in',
    category: '页面设置',
    priority: 9,
    outputFormats: ['pdf'],
  },
  {
    id: 'margin-left',
    name: '--margin-left',
    type: 'value',
    valueType: 'string',
    label: '左边距',
    description: '设置页面左边距',
    placeholder: '如 2cm 或 1in',
    category: '页面设置',
    priority: 10,
    outputFormats: ['pdf'],
  },
  {
    id: 'margin-right',
    name: '--margin-right',
    type: 'value',
    valueType: 'string',
    label: '右边距',
    description: '设置页面右边距',
    placeholder: '如 2cm 或 1in',
    category: '页面设置',
    priority: 11,
    outputFormats: ['pdf'],
  },
  {
    id: 'columns',
    name: '--columns',
    type: 'value',
    valueType: 'number',
    label: '分栏数',
    description: '设置页面分栏数量',
    defaultValue: 1,
    placeholder: '输入分栏数',
    category: '页面设置',
    priority: 12,
    outputFormats: ['pdf'],
  },
  {
    id: 'dpi',
    name: '--dpi',
    type: 'value',
    valueType: 'number',
    label: '图片DPI',
    description: '设置图片的分辨率',
    defaultValue: 300,
    placeholder: '输入DPI值',
    category: '页面设置',
    priority: 13,
    outputFormats: ['pdf'],
  },
  {
    id: 'template',
    name: '--template',
    type: 'value',
    valueType: 'path',
    label: '自定义模板',
    description: '使用自定义模板文件',
    placeholder: '选择模板文件',
    category: '模板样式',
    priority: 14,
  },
  {
    id: 'css',
    name: '--css',
    type: 'value',
    valueType: 'path',
    label: 'CSS样式',
    description: '为 HTML 输出指定 CSS 样式文件',
    placeholder: '选择CSS文件',
    category: '模板样式',
    priority: 15,
    outputFormats: ['html'],
  },
  {
    id: 'reference-doc',
    name: '--reference-doc',
    type: 'value',
    valueType: 'path',
    label: '参考文档',
    description: '使用 Word 文档作为样式参考',
    placeholder: '选择Word文档',
    category: '模板样式',
    priority: 16,
  },
  {
    id: 'highlight-style',
    name: '--highlight-style',
    type: 'value',
    valueType: 'select',
    label: '代码高亮',
    description: '设置代码块语法高亮主题',
    defaultValue: 'pygments',
    options: ['pygments', 'kate', 'monochrome', 'tango', 'espresso', 'zenburn', 'haddock'],
    category: '常用参数',
    priority: 6,
  },
  {
    id: 'syntax-definition',
    name: '--syntax-definition',
    type: 'value',
    valueType: 'path',
    label: '语法定义',
    description: '使用自定义语法高亮定义文件',
    placeholder: '选择XML文件',
    category: '模板样式',
    priority: 17,
  },
  {
    id: 'citeproc',
    name: '--citeproc',
    type: 'flag',
    valueType: 'boolean',
    label: '引用处理',
    description: '启用 CiteProc 引用处理',
    category: '文献引用',
    priority: 18,
  },
  {
    id: 'bibliography',
    name: '--bibliography',
    type: 'value',
    valueType: 'path',
    label: '参考文献',
    description: '指定参考文献文件',
    placeholder: '选择.bib或.json文件',
    category: '文献引用',
    priority: 19,
  },
  {
    id: 'csl',
    name: '--csl',
    type: 'value',
    valueType: 'path',
    label: '引用样式',
    description: '指定 CSL 引用样式文件',
    placeholder: '选择.csl文件',
    category: '文献引用',
    priority: 20,
  },
  {
    id: 'natbib',
    name: '--natbib',
    type: 'flag',
    valueType: 'boolean',
    label: 'Natbib格式',
    description: '使用 natbib 格式处理引用',
    category: '文献引用',
    priority: 21,
  },
  {
    id: 'biblatex',
    name: '--biblatex',
    type: 'flag',
    valueType: 'boolean',
    label: 'BibLaTeX格式',
    description: '使用 biblatex 格式处理引用',
    category: '文献引用',
    priority: 22,
  },
  {
    id: 'listings',
    name: '--listings',
    type: 'flag',
    valueType: 'boolean',
    label: 'LaTeX Listings',
    description: '使用 LaTeX listings 包处理代码',
    category: '代码数学',
    priority: 23,
  },
  {
    id: 'mathjax',
    name: '--mathjax',
    type: 'flag',
    valueType: 'boolean',
    label: 'MathJax',
    description: '使用 MathJax 渲染数学公式',
    category: '代码数学',
    priority: 24,
  },
  {
    id: 'katex',
    name: '--katex',
    type: 'flag',
    valueType: 'boolean',
    label: 'KaTeX',
    description: '使用 KaTeX 渲染数学公式',
    category: '代码数学',
    priority: 25,
  },
  {
    id: 'webtex',
    name: '--webtex',
    type: 'flag',
    valueType: 'boolean',
    label: 'WebTeX',
    description: '使用在线服务渲染数学公式',
    category: '代码数学',
    priority: 26,
  },
  {
    id: 'gladtex',
    name: '--gladtex',
    type: 'flag',
    valueType: 'boolean',
    label: 'GladTeX',
    description: '使用 GladTeX 渲染数学公式',
    category: '代码数学',
    priority: 27,
  },
  {
    id: 'filter',
    name: '--filter',
    type: 'value',
    valueType: 'string',
    label: '过滤器',
    description: '运行外部过滤器程序',
    placeholder: '如 pandoc-citeproc',
    category: '过滤扩展',
    priority: 28,
  },
  {
    id: 'lua-filter',
    name: '--lua-filter',
    type: 'value',
    valueType: 'path',
    label: 'Lua过滤器',
    description: '运行 Lua 过滤器脚本',
    placeholder: '选择.lua文件',
    category: '过滤扩展',
    priority: 29,
  },
  {
    id: 'include-in-header',
    name: '--include-in-header',
    type: 'value',
    valueType: 'path',
    label: '头部插入',
    description: '在文档头部插入内容',
    placeholder: '选择文件',
    category: '过滤扩展',
    priority: 30,
  },
  {
    id: 'include-before-body',
    name: '--include-before-body',
    type: 'value',
    valueType: 'path',
    label: '正文前插入',
    description: '在正文前插入内容',
    placeholder: '选择文件',
    category: '过滤扩展',
    priority: 31,
  },
  {
    id: 'include-after-body',
    name: '--include-after-body',
    type: 'value',
    valueType: 'path',
    label: '正文后插入',
    description: '在正文后插入内容',
    placeholder: '选择文件',
    category: '过滤扩展',
    priority: 32,
  },
  {
    id: 'wrap',
    name: '--wrap',
    type: 'value',
    valueType: 'select',
    label: '文本换行',
    description: '设置文本换行方式',
    defaultValue: 'auto',
    options: ['auto', 'none', 'preserve'],
    category: '输出控制',
    priority: 33,
  },
  {
    id: 'tab-stop',
    name: '--tab-stop',
    type: 'value',
    valueType: 'number',
    label: 'Tab宽度',
    description: '设置 Tab 字符宽度',
    defaultValue: 4,
    placeholder: '输入Tab宽度',
    category: '输出控制',
    priority: 34,
  },
  {
    id: 'pdf-engine',
    name: '--pdf-engine',
    type: 'value',
    valueType: 'select',
    label: 'PDF引擎',
    description: '指定 PDF 生成引擎',
    defaultValue: 'xelatex',
    options: ['xelatex', 'lualatex', 'pdflatex', 'latex', 'wkhtmltopdf', 'weasyprint'],
    category: '输出控制',
    priority: 35,
  },
  {
    id: 'resource-path',
    name: '--resource-path',
    type: 'value',
    valueType: 'string',
    label: '资源路径',
    description: '设置资源文件搜索路径',
    placeholder: '如 .:images:assets',
    category: '输出控制',
    priority: 36,
  },
  {
    id: 'extract-media',
    name: '--extract-media',
    type: 'value',
    valueType: 'path',
    label: '提取媒体',
    description: '将媒体文件提取到指定目录',
    placeholder: '选择目录',
    category: '输出控制',
    priority: 37,
  },
]

export const CATEGORIES = [
  '常用参数',
  '文档结构',
  '页面设置',
  '模板样式',
  '文献引用',
  '代码数学',
  '过滤扩展',
  '输出控制',
]

export function getParamById(id: string): ParamDefinition | undefined {
  return PARAM_DEFINITIONS.find(p => p.id === id)
}

export function getParamsByCategory(category: string): ParamDefinition[] {
  return PARAM_DEFINITIONS.filter(p => p.category === category)
}

export function searchParams(query: string): ParamDefinition[] {
  const lowerQuery = query.toLowerCase()
  return PARAM_DEFINITIONS.filter(p =>
    p.name.toLowerCase().includes(lowerQuery) ||
    p.label.toLowerCase().includes(lowerQuery) ||
    p.description.toLowerCase().includes(lowerQuery)
  ).sort((a, b) => (a.priority || 999) - (b.priority || 999))
}

export function isParamVisible(
  param: ParamDefinition,
  selectedParams: { id: string; value: any }[],
  outputFormat: string
): boolean {
  if (param.dependencies && param.dependencies.length > 0) {
    const allDependenciesMet = param.dependencies.every(depId => {
      const depParam = selectedParams.find(p => p.id === depId)
      return depParam && depParam.value === true
    })
    if (!allDependenciesMet) return false
  }

  if (param.outputFormats && param.outputFormats.length > 0) {
    if (!param.outputFormats.includes(outputFormat)) return false
  }

  return true
}
